; Unified PokeyVQ Player Wrapper
; Uses VQ_CFG.asm for configuration
; Generated by PokeyVQ CLI

    DEBUG_COMPILATION = 1

    icl "VQ_CFG.asm"
    icl "common/atari.inc"
    icl "common/zeropage.inc"
    icl "common/copy_os_ram.asm"

    ORG $2000

.ifdef DEBUG_COMPILATION
    .print " "
    .print "--- POKEY VQ PLAYER BUILD ---"
    .print "Start at: ", *
.endif

; Display List (Simple)
dlist:
    .byte $70,$70,$70
    .byte $41,<dlist,>dlist

    ; --- Compile-Time Checks ---
    .ifndef PLAY_RATE
        .error "PLAY_RATE must be defined in VQ_CFG.asm"
    .endif

    ; Main Entry
start:
    ; Minimal initialization
    sei    
    lda #$00   ; Disable IRQ
    sta IRQEN
    lda #$FE   ; Enable RAM
    sta PORTB  

    lda #<nmi
    sta $fffa
    lda #>nmi
    sta $fffa+1

    lda #<PokeyVQ_IRQ ; Defined in common/vq_player.asm
    sta $fffe
    lda #>PokeyVQ_IRQ ; Defined in common/vq_player.asm
    sta $fffe+1

    ; Display List
    lda #<dlist
    sta DLISTL
    lda #>dlist
    sta DLISTH
    lda #34    ; Enable DMA
    sta DMACTL
    lda #$C0   ; Enable NMI (VBI + DLI)
    sta NMIEN
    cli

    jsr PokeyVQ_Init ; Implemented in common/vq_player.asm

    ; Main Loop
    lda #$40
forever:
    sta COLBK
    jmp forever

nmi:
    rti ; Minimal NMI

    ; --- Include The Core Player Engine ---
.ifdef DEBUG_COMPILATION
    .print "Including Core Player Engine..."
.endif
    icl "common/vq_player.asm"

; --- Data Includes ---
    
.ifdef DEBUG_COMPILATION
    .print "Data Origin: ", *
.endif
    
.ifdef ALGO_RAW
    icl "RAW_DATA.asm"
.else
    icl "VQ_LENS.asm"
    icl "VQ_LO.asm"
    icl "VQ_HI.asm"
    icl "VQ_BLOB.asm"
    icl "VQ_INDICES.asm"
.endif

.if CHANNELS == 1
.ifdef USE_FAST_CPU
    icl "LUT_NIBBLES.asm"
.endif
.endif

.ifdef DEBUG_COMPILATION
    .print "End of Data: ", *
.endif

    .if * >= $C000
        .print "Data section too large by ", *-$C000
        .error "Lower Quality or playback Rate"
    .endif

    run start
