; Multi-Sample Directory
; Generated by PokeyVQ

SAMPLE_COUNT = 20
; MULTI_SAMPLE is defined in VQ_CFG.asm

SAMPLE_START_LO
 .byte <(VQ_INDICES+$0000) ; AnalogString.wav
 .byte <(VQ_INDICES+$0316) ; BassDrum3.wav
 .byte <(VQ_INDICES+$0447) ; Claps1.wav
 .byte <(VQ_INDICES+$0515) ; DeepBass.wav
 .byte <(VQ_INDICES+$07F5) ; Detune.wav
 .byte <(VQ_INDICES+$09F5) ; EPiano.wav
 .byte <(VQ_INDICES+$0CC3) ; HeavySynth.wav
 .byte <(VQ_INDICES+$1033) ; Snare3.wav
 .byte <(VQ_INDICES+$1188) ; Snare4.wav
 .byte <(VQ_INDICES+$123C) ; Snare5.wav
 .byte <(VQ_INDICES+$13A3) ; SoftBass.wav
 .byte <(VQ_INDICES+$155B) ; Strings5.wav
 .byte <(VQ_INDICES+$18D4) ; WowBass.wav
 .byte <(VQ_INDICES+$1A95) ; bdrumyepp001.wav
 .byte <(VQ_INDICES+$1D63) ; kef1tensebass.wav
 .byte <(VQ_INDICES+$2A9A) ; searsnare2.wav
 .byte <(VQ_INDICES+$2D6B) ; seartomtom.wav
 .byte <(VQ_INDICES+$3026) ; slapbass2.wav
 .byte <(VQ_INDICES+$3396) ; slight_string002.wav
 .byte <(VQ_INDICES+$4249) ; wsnare1.wav

SAMPLE_START_HI
 .byte >(VQ_INDICES+$0000) ; AnalogString.wav
 .byte >(VQ_INDICES+$0316) ; BassDrum3.wav
 .byte >(VQ_INDICES+$0447) ; Claps1.wav
 .byte >(VQ_INDICES+$0515) ; DeepBass.wav
 .byte >(VQ_INDICES+$07F5) ; Detune.wav
 .byte >(VQ_INDICES+$09F5) ; EPiano.wav
 .byte >(VQ_INDICES+$0CC3) ; HeavySynth.wav
 .byte >(VQ_INDICES+$1033) ; Snare3.wav
 .byte >(VQ_INDICES+$1188) ; Snare4.wav
 .byte >(VQ_INDICES+$123C) ; Snare5.wav
 .byte >(VQ_INDICES+$13A3) ; SoftBass.wav
 .byte >(VQ_INDICES+$155B) ; Strings5.wav
 .byte >(VQ_INDICES+$18D4) ; WowBass.wav
 .byte >(VQ_INDICES+$1A95) ; bdrumyepp001.wav
 .byte >(VQ_INDICES+$1D63) ; kef1tensebass.wav
 .byte >(VQ_INDICES+$2A9A) ; searsnare2.wav
 .byte >(VQ_INDICES+$2D6B) ; seartomtom.wav
 .byte >(VQ_INDICES+$3026) ; slapbass2.wav
 .byte >(VQ_INDICES+$3396) ; slight_string002.wav
 .byte >(VQ_INDICES+$4249) ; wsnare1.wav

SAMPLE_END_LO
 .byte <(VQ_INDICES+$0316) ; AnalogString.wav
 .byte <(VQ_INDICES+$0447) ; BassDrum3.wav
 .byte <(VQ_INDICES+$0515) ; Claps1.wav
 .byte <(VQ_INDICES+$07F5) ; DeepBass.wav
 .byte <(VQ_INDICES+$09F5) ; Detune.wav
 .byte <(VQ_INDICES+$0CC3) ; EPiano.wav
 .byte <(VQ_INDICES+$1033) ; HeavySynth.wav
 .byte <(VQ_INDICES+$1188) ; Snare3.wav
 .byte <(VQ_INDICES+$123C) ; Snare4.wav
 .byte <(VQ_INDICES+$13A3) ; Snare5.wav
 .byte <(VQ_INDICES+$155B) ; SoftBass.wav
 .byte <(VQ_INDICES+$18D4) ; Strings5.wav
 .byte <(VQ_INDICES+$1A95) ; WowBass.wav
 .byte <(VQ_INDICES+$1D63) ; bdrumyepp001.wav
 .byte <(VQ_INDICES+$2A9A) ; kef1tensebass.wav
 .byte <(VQ_INDICES+$2D6B) ; searsnare2.wav
 .byte <(VQ_INDICES+$3026) ; seartomtom.wav
 .byte <(VQ_INDICES+$3396) ; slapbass2.wav
 .byte <(VQ_INDICES+$4249) ; slight_string002.wav
 .byte <(VQ_INDICES+$43ED) ; wsnare1.wav

SAMPLE_END_HI
 .byte >(VQ_INDICES+$0316) ; AnalogString.wav
 .byte >(VQ_INDICES+$0447) ; BassDrum3.wav
 .byte >(VQ_INDICES+$0515) ; Claps1.wav
 .byte >(VQ_INDICES+$07F5) ; DeepBass.wav
 .byte >(VQ_INDICES+$09F5) ; Detune.wav
 .byte >(VQ_INDICES+$0CC3) ; EPiano.wav
 .byte >(VQ_INDICES+$1033) ; HeavySynth.wav
 .byte >(VQ_INDICES+$1188) ; Snare3.wav
 .byte >(VQ_INDICES+$123C) ; Snare4.wav
 .byte >(VQ_INDICES+$13A3) ; Snare5.wav
 .byte >(VQ_INDICES+$155B) ; SoftBass.wav
 .byte >(VQ_INDICES+$18D4) ; Strings5.wav
 .byte >(VQ_INDICES+$1A95) ; WowBass.wav
 .byte >(VQ_INDICES+$1D63) ; bdrumyepp001.wav
 .byte >(VQ_INDICES+$2A9A) ; kef1tensebass.wav
 .byte >(VQ_INDICES+$2D6B) ; searsnare2.wav
 .byte >(VQ_INDICES+$3026) ; seartomtom.wav
 .byte >(VQ_INDICES+$3396) ; slapbass2.wav
 .byte >(VQ_INDICES+$4249) ; slight_string002.wav
 .byte >(VQ_INDICES+$43ED) ; wsnare1.wav